
/**
  @author Rahul S. Sampath
  */

#ifndef _MPI_CONST
#define _MPI_CONST

//Neighbors

const char _NH_DIR_STR[2][4] = { "NEG", "POS" };

enum NH_ID_2D
{
    _NH_ID_2D_NEGX_NEGZ,
    _NH_ID_2D_CENX_NEGZ,
    _NH_ID_2D_POSX_NEGZ,
    _NH_ID_2D_NEGX_CENZ,
    _NH_ID_2D_POSX_CENZ,
    _NH_ID_2D_NEGX_POSZ,
    _NH_ID_2D_CENX_POSZ,
    _NH_ID_2D_POSX_POSZ,
    _NH_ID_2D_TOTAL
};

const NH_ID_2D NH_ID_2D_MAP[_NH_ID_2D_TOTAL] = { _NH_ID_2D_NEGX_NEGZ, _NH_ID_2D_CENX_NEGZ, _NH_ID_2D_POSX_NEGZ,
                                                 _NH_ID_2D_NEGX_CENZ, _NH_ID_2D_POSX_CENZ, _NH_ID_2D_NEGX_POSZ,
                                                 _NH_ID_2D_CENX_POSZ, _NH_ID_2D_POSX_POSZ };

const NH_ID_2D INV_NH_ID_2D[_NH_ID_2D_TOTAL] = { _NH_ID_2D_POSX_POSZ, _NH_ID_2D_CENX_POSZ, _NH_ID_2D_NEGX_POSZ,
                                                 _NH_ID_2D_POSX_CENZ, _NH_ID_2D_NEGX_CENZ, _NH_ID_2D_POSX_NEGZ,
                                                 _NH_ID_2D_CENX_NEGZ, _NH_ID_2D_NEGX_NEGZ };

const char _NH_ID_STR_2D[_NH_ID_2D_TOTAL][10] = { "NEGX_NEGZ", "CENX_NEGZ", "POSX_NEGZ", "NEGX_CENZ",
                                                  "POSX_CENZ", "NEGX_POSZ", "CENX_POSZ", "POSX_POSZ" };

enum NH_ID_3D
{
    _NH_ID_3D_NEGX_NEGY_NEGZ,
    _NH_ID_3D_CENX_NEGY_NEGZ,
    _NH_ID_3D_POSX_NEGY_NEGZ,
    _NH_ID_3D_NEGX_CENY_NEGZ,
    _NH_ID_3D_CENX_CENY_NEGZ,
    _NH_ID_3D_POSX_CENY_NEGZ,
    _NH_ID_3D_NEGX_POSY_NEGZ,
    _NH_ID_3D_CENX_POSY_NEGZ,
    _NH_ID_3D_POSX_POSY_NEGZ,
    _NH_ID_3D_NEGX_NEGY_CENZ,
    _NH_ID_3D_CENX_NEGY_CENZ,
    _NH_ID_3D_POSX_NEGY_CENZ,
    _NH_ID_3D_NEGX_CENY_CENZ,
    _NH_ID_3D_POSX_CENY_CENZ,
    _NH_ID_3D_NEGX_POSY_CENZ,
    _NH_ID_3D_CENX_POSY_CENZ,
    _NH_ID_3D_POSX_POSY_CENZ,
    _NH_ID_3D_NEGX_NEGY_POSZ,
    _NH_ID_3D_CENX_NEGY_POSZ,
    _NH_ID_3D_POSX_NEGY_POSZ,
    _NH_ID_3D_NEGX_CENY_POSZ,
    _NH_ID_3D_CENX_CENY_POSZ,
    _NH_ID_3D_POSX_CENY_POSZ,
    _NH_ID_3D_NEGX_POSY_POSZ,
    _NH_ID_3D_CENX_POSY_POSZ,
    _NH_ID_3D_POSX_POSY_POSZ,
    _NH_ID_3D_TOTAL
};

const NH_ID_3D NH_ID_3D_MAP[_NH_ID_3D_TOTAL] = {
    _NH_ID_3D_NEGX_NEGY_NEGZ, _NH_ID_3D_CENX_NEGY_NEGZ, _NH_ID_3D_POSX_NEGY_NEGZ, _NH_ID_3D_NEGX_CENY_NEGZ,
    _NH_ID_3D_CENX_CENY_NEGZ, _NH_ID_3D_POSX_CENY_NEGZ, _NH_ID_3D_NEGX_POSY_NEGZ, _NH_ID_3D_CENX_POSY_NEGZ,
    _NH_ID_3D_POSX_POSY_NEGZ, _NH_ID_3D_NEGX_NEGY_CENZ, _NH_ID_3D_CENX_NEGY_CENZ, _NH_ID_3D_POSX_NEGY_CENZ,
    _NH_ID_3D_NEGX_CENY_CENZ, _NH_ID_3D_POSX_CENY_CENZ, _NH_ID_3D_NEGX_POSY_CENZ, _NH_ID_3D_CENX_POSY_CENZ,
    _NH_ID_3D_POSX_POSY_CENZ, _NH_ID_3D_NEGX_NEGY_POSZ, _NH_ID_3D_CENX_NEGY_POSZ, _NH_ID_3D_POSX_NEGY_POSZ,
    _NH_ID_3D_NEGX_CENY_POSZ, _NH_ID_3D_CENX_CENY_POSZ, _NH_ID_3D_POSX_CENY_POSZ, _NH_ID_3D_NEGX_POSY_POSZ,
    _NH_ID_3D_CENX_POSY_POSZ, _NH_ID_3D_POSX_POSY_POSZ
};

const NH_ID_3D INV_NH_ID_3D[_NH_ID_3D_TOTAL] = {
    _NH_ID_3D_POSX_POSY_POSZ, _NH_ID_3D_CENX_POSY_POSZ, _NH_ID_3D_NEGX_POSY_POSZ, _NH_ID_3D_POSX_CENY_POSZ,
    _NH_ID_3D_CENX_CENY_POSZ, _NH_ID_3D_NEGX_CENY_POSZ, _NH_ID_3D_POSX_NEGY_POSZ, _NH_ID_3D_CENX_NEGY_POSZ,
    _NH_ID_3D_NEGX_NEGY_POSZ, _NH_ID_3D_POSX_POSY_CENZ, _NH_ID_3D_CENX_POSY_CENZ, _NH_ID_3D_NEGX_POSY_CENZ,
    _NH_ID_3D_POSX_CENY_CENZ, _NH_ID_3D_NEGX_CENY_CENZ, _NH_ID_3D_POSX_NEGY_CENZ, _NH_ID_3D_CENX_NEGY_CENZ,
    _NH_ID_3D_NEGX_NEGY_CENZ, _NH_ID_3D_POSX_POSY_NEGZ, _NH_ID_3D_CENX_POSY_NEGZ, _NH_ID_3D_NEGX_POSY_NEGZ,
    _NH_ID_3D_POSX_CENY_NEGZ, _NH_ID_3D_CENX_CENY_NEGZ, _NH_ID_3D_NEGX_CENY_NEGZ, _NH_ID_3D_POSX_NEGY_NEGZ,
    _NH_ID_3D_CENX_NEGY_NEGZ, _NH_ID_3D_NEGX_NEGY_NEGZ
};

const char _NH_ID_STR_3D[_NH_ID_3D_TOTAL][15] = {
    "NEGX_NEGY_NEGZ", "CENX_NEGY_NEGZ", "POSX_NEGY_NEGZ", "NEGX_CENY_NEGZ", "CENX_CENY_NEGZ", "POSX_CENY_NEGZ",
    "NEGX_POSY_NEGZ", "CENX_POSY_NEGZ", "POSX_POSY_NEGZ", "NEGX_NEGY_CENZ", "CENX_NEGY_CENZ", "POSX_NEGY_CENZ",
    "NEGX_CENY_CENZ", "POSX_CENY_CENZ", "NEGX_POSY_CENZ", "CENX_POSY_CENZ", "POSX_POSY_CENZ", "NEGX_NEGY_POSZ",
    "CENX_NEGY_POSZ", "POSX_NEGY_POSZ", "NEGX_CENY_POSZ", "CENX_CENY_POSZ", "POSX_CENY_POSZ", "NEGX_POSY_POSZ",
    "CENX_POSY_POSZ", "POSX_POSY_POSZ"
};

#endif
